function ian(){
    document.getElementById('szoveg').innerHTML = " <p id='aham'> <b> Ian Somerhalder a Louisiana állami Covingtonban született és nevelkedett, Edna és Robert Somerhalder fiaként. Anyja masszőr, apja pedig építési vállalkozó. <br> Katolikusként nevelték, és egy covingtoni katolikus magániskolában, a St. Pauls Schoolban tanult. Tíz és tizenhárom éves kora között modellkedett,Tizenhárom éves volt, amikor szülei elváltak, és ő édesanyjával maradt. Tizenhét éves korában a színészkedés mellett döntött. Somerhalder játszott a Will és a haverok (Young Americans) című rövid életű sorozatban, amely a Dawson és a haverok (Dawson's Creek) című sorozat spin-offja volt. Egy tekintélyes bentlakásos iskola igazgatójának a fiát, Hamilton Fleminget alakította. 2002-ben Paul Dentont alakította A vonzás szabályai (The Rules of Attraction) című Bret Easton Ellis-regény feldolgozásában. A filmben együtt játszott James Van Der Beekkel, Shannyn Sossamonnal és Jessica Biellel.2004-ben megkapta az áttörést hozó szerepét Boone Carlyle-ként a Lost – Eltűntek című tévésorozatban. Annak ellenére, hogy a karaktere meghalt az első évad huszadik epizódjában, Somerhalder visszatért még kilenc epizódba 2005 és 2010 között, beleértve a sorozat fináléját is. Ironikus, hogy Somerhalder volt az első színész, akit beválogattak a sorozatba, és az ő karaktere halt meg legelőször. Azt nyilatkozta, hogy szeretett volna venni egy házat a forgatás helyszínén, Hawaii-on, amíg meg nem tudta, hogy a karaktere meg fog halni.Somerhaldert 2006 májusában a DNA Model Management top 10 férfi modellje közé sorolták.2009 szeptemberében szerepelt a Bérgyilkosok viadala (The Tournament) című filmben, melyben egy olyan bérgyilkost alakított, aki részt vett egy más bérgyilkosokkal folytatott halálos versenyben. 2009. október 10-én bejelentették, hogy szerepelni fog a Cradlewood című filmben, melyet Harry Weinmann rendez. A filmet 2012-ben fogják kiadni.Somerhalder a Vámpírnaplók (The Vampire Diaries) című sorozatban Damon Salvatore-t formálta meg. A karaktere egy veszélyes, őrült, de humoros és őszinte vámpír, aki szerelmes az öccse barátnőjébe, Elena Gilbertbe (Nina Dobrev), akivel később össze is jön.</b> </p>"
    document.getElementById("nev").innerHTML = "<h1 id='nevek'>Ian Somerhalder   "
}

function nina(){
    document.getElementById('szoveg').innerHTML ="<p id='aham'> <b> Dobrev a bulgáriai Szófiában született. 2 éves korában Kanadába költöztek, ahol az Ontario tartománybeli Torontóban nevelkedett. Folyékonyan beszél franciául, angolul és bolgárul. Édesanyja művész, míg édesapja számítógép-tudománnyal foglalkozik. Van egy bátyja, Aleksander, aki mérnöknek tanul. Már nagyon fiatalon kimutatta lelkesedését és tehetségét a művészetek – a tánc, a torna, a színészet, a festészet és a zene – iránt.Dobrev a J. B. Tyrrell Sr. Iskolába, majd a Wexford Művészeti Iskolába járt a végzős évéig az Ontario tartományi Scarborough-ban. A torontói Ryerson Egyetemen szociológiát tanult. 2008-ban otthagyta az egyetemet, hogy a színészi pályát folytassa.Dobrev eleinte modellkedéssel próbálkozott. Az így kapott reklámszerepei miatt felfigyeltek rá, és ezután kapott néhány kisebb filmszerepet. Első jelentősebb szerepét A Degrassi gimi (Degrassi: The Next Generation) című tévésorozatban kapta, melyben 2006 és 2009 között Mia Jones, egy szingli tinédzser anya szerepét játszotta. 2007-ben több filmben is szerepelt: A költő (The Poet), a Korai neked még a konty! (Too Young to Marry) és az Ártatlanul vádolva (My Daughter's Secret) című filmekben a főszerepet játszotta; a Fugitive Pieces című drámában pedig egy kisebb szerepet kapott. 2008-ban két tévéfilmben is főszereplő volt: a Ne kiálts vérfarkast! című horrorban a 16 éves Loren Hansettet alakította; majd a The American Mall című musical filmben Ally karakterét formálta meg. 2009-ben újra Mia Jones szerepét játszotta a Degrassi Goes Hollywood című tévéfilmben, majd még ugyanebben az évben egy kisebb szerepet játszott a Chloe - A kísértés iskolája című erotikus thrillerben. Szintén 2009-ben ő adta Kupidó, a rénszarvas hangját a MadagaszKarácsony (Merry Madagascar) című rövidfilmben.Dobrev 2009-től a Vámpírnaplók (The Vampire Diaries) című tévésorozatban két karaktert is megformál: a főszereplőt, Elena Gilbertet és Katherine Pierce-t, akinek Elena a hasonmása. A sorozat középpontjában az Elena és a két vámpír, Stefan és Damon Salvatore között kialakuló szerelmi háromszög áll. Dobrev a drámában nyújtott alakításáért két Teen Choice-díjat is kapott 2010-ben, mint a legjobb új női szereplő, és mint a legjobb női szereplő fantasy/sci-fi tévésorozatban. "
    document.getElementById("nev").innerHTML = "<h1 id='nevek'>Nina Dobrev</h1> "

}

function paul(){
    document.getElementById('szoveg').innerHTML = "<p  id='aham'><b>Paul Thomas Wasilewski, ismertebb nevén Paul Wesley (New Brunswick, New Jersey, 1982. július 23. –) amerikai színész.Elsősorban a Vámpírnaplók (2009–2017) című tévésorozatból, Stefan Salvatore szerepében ismert. Feltűnt a Fallen – Letaszítva (2007), a Katonafeleségek (2008–2009), a Mondj egy mesét (2018–2020) és 2022-től a Star Trek: Különös új világok című sorozatokban is.A Christian Brothers Academy-ra járt a New Jersey állami Lincroftban, és középiskolai évei közül néhányat a Marlboro High Schoolban töltött. A középiskolai harmadik évében szerepelt a Guiding Light című szappanoperában Max Nickersont formálta meg. A Marlboro High Schoolból átiratkozott a Lakewood Prep Schoolba, mely a New Jersey állami Howellben volt. Ennek az oka az volt, hogy az új iskolája képes volt alkalmazkodni a színészkedési programjaihoz.Ott 2000-ben érettségizett, majd egy félévig a Rutgers University-n tanult. A szülei támogatásával hagyta ott az egyetemet, amikor több szerepet ajánlottak fel neki, és rájött, hogy a színészettel is tud karriert építeni. 2005-ben kezdett Paul Wesley néven színészkedni. Amikor megkérdezték tőle, hogy miért változtatta meg a nevét, így nyilatkozott: „a születési nevemet túl nehéz kiejteni! A családom beleegyezését kértem, hogy megváltoztathassam, és tényleg segítette a karrieremet.Szerepelt olyan sorozatokban, mint a 24, a Pimaszok, avagy kamaszba nem üt a mennykő, az American Dreams, a Katonafeleségek, a Cane, az Everwood, a Vezérlő fény, a Smallville, A narancsvidék és a Wolf Lake. Szintén szerepelt Amber Tamblyn mellett a The Russell Girl című filmben, és a Fallen – Letaszítva című minisorozatban főszerepet játszott.2009 és 2017 között a Vámpírnaplók című sorozatban Stefan Salvatore vámpírt formálta meg. A sorozat 2009 szeptemberében kezdődött a The CW filmcsatornán. 2012-ben szerepelt a The Baytown Disco című filmben.</b> </p>"
    document.getElementById("nev").innerHTML = "<h1 id='nevek'>Paul Wesley</h1> <br> > "
}

